baseURL = "https://www.gollahalli.com/"
languageCode = "en-us"
title = "Akshay Raj Gollahalli"
theme = "spark"

googleAnalytics = "G-7WDESHJKMH"   # Optional
disqusShortname = "gollahalli-com" # Optional
pygmentsCodeFences = true
enableRobotsTXT = true
enableEmoji = true

[pagination]
pagerSize = 12

[markup]
[markup.highlight]
style = "github-dark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
linkify = false
[markup.goldmark.extensions.passthrough]
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\\(', '\\)'], ['$', '$']]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[outputFormats]
[outputFormats.searchindex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
[outputFormats.ads]
mediaType = "text/plain"
baseName = "ads"
isPlainText = true


[mediaTypes]
[mediaTypes."font/woff"]
suffixes = ["woff"]
[mediaTypes."font/woff2"]
suffixes = ["woff2"]

[outputs]
home = ["HTML", "RSS", "searchindex", "ads"]
page = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[params]
googleAds = "7450383714878520"                          # Optional, ignore "ca-pub-"
repo = "https://github.com/akshaybabloo/gollahalli.com"
year = 2024
email = "akshay@gollahalli.com"                 # Optional
#    pgp = "3570 2F7C E0CF 2579 BF7D 05DD A603 9E24 179E E13D" # Optional
# logoSVG = "img/logo.svg" # # Use logoSVG or logo. Optional
# logo = "" # Use logoSVG or logo. Optional
namedLogo = "/img/logo.svg"
logoPhoto = "/img/akshay.jpg"                          # Use logoSVG or logo or logoPhoto. Optional
algoliaAppId = "UT1XVMZE1Q"
algoliaApiKey = "fadcde84f1cdaf165d51c20a50336188"
algoliaIndexName = "gollahalli-website"
thumbnailUrl = "/img/akshay.jpg"
acknowledge = false
convertAssetsToInline = false                          # Converts external assets into minified inline assets
cloudflareInsight = "83b998816e3e4417be0a7582d7645cd3"
clarity = "im383wjll4"

[params.social]
github = "https://github.com/akshaybabloo"      # Optional
linkedin = "https://linkedin.com/in/gollahalli" # Optional
twitter = "http://twitter.com/akshaybabloo"     # Optional

# [params.profiles]
# googleScholar = "https://scholar.google.com/citations?user=VXn8sR8AAAAJ&hl=en"
# researchGate = "https://www.researchgate.net/profile/Akshay_Gollahalli"
# orcid = "https://orcid.org/0000-0003-2306-3850"

[params.sponsor]
enable = true
link = "https://github.com/sponsors/akshaybabloo"

[params.alert]
body = "Stay home, protect yourself and everyone around you from COVID-19. For more information see - <a href='https://www.who.int/emergencies/diseases/novel-coronavirus-2019'>www.who.int/emergencies/diseases/novel-coronavirus-2019</a>"
type = "danger"
icon = ""

[params.sectionThemes]
    [params.sectionThemes.default] # Ruby Red (Home)
    accent = "#fb7185"
    bg = "#4c0519"
    surface = "#881337"
    surfaceHover = "#9f1239"
    textSecondary = "#ffe4e6" # Rose 100
    textMuted = "#fb7185"     # Rose 400 (Darker/Saturated)

    [params.sectionThemes.projects] # Sapphire Blue
    accent = "#60a5fa"
    bg = "#172554"
    surface = "#1e3a8a"
    surfaceHover = "#1d4ed8"
    textSecondary = "#dbeafe" # Blue 100
    textMuted = "#93c5fd"     # Blue 300 (Brighter)

    [params.sectionThemes.blog] # Amethyst Purple
    accent = "#c084fc"
    bg = "#3b0764"
    surface = "#581c87"
    surfaceHover = "#6b21a8"
    textSecondary = "#f3e8ff" # Purple 100
    textMuted = "#d8b4fe"     # Purple 300 (High Contrast)

    [params.sectionThemes.publications] # Topaz/Bronze
    accent = "#fbbf24"
    bg = "#451a03"
    surface = "#78350f"
    surfaceHover = "#92400e"
    textSecondary = "#e7e5e4" # Stone 200
    textMuted = "#a8a29e"     # Stone 400

    [params.sectionThemes.about] # Emerald Green
    accent = "#34d399"
    bg = "#022c22"
    surface = "#064e3b"
    surfaceHover = "#065f46"
    textSecondary = "#ecfdf5" # Emerald 50
    textMuted = "#34d399"     # Emerald 400

[params.seo]
noIndexTags = true
noIndexCategories = true
